source $HOME/.config/nvim/configs/plugins.vim
source $HOME/.config/nvim/configs/defaults.vim
source $HOME/.config/nvim/configs/nerdtree.vim
source $HOME/.config/nvim/configs/airline.vim
source $HOME/.config/nvim/configs/ale.vim
source $HOME/.config/nvim/configs/quickui.vim
source $HOME/.config/nvim/configs/neoterm.vim
source $HOME/.config/nvim/configs/indent_line.vim
source $HOME/.config/nvim/configs/keys.vim
